
/*
    Problem 2: Even Fibonacci numbers

    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
                        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    https://projecteuler.net/problem=2

*/

// find sum of even term does not exceed n
function fibonacci(n)
{
    // previous value
    var a = 1;
    // current value
    var b = 2;
    var sum = 0;
    while(a < n)
    {
        if(a%2 == 0)
        {
            sum = sum + a;
        }

        // next value
        var t = b;
        b = a + b;
        a = t;
    }
    return sum;
}

fibonacci(4e6);

//Answer: 4613732